baseurl = "/"
title = "Angela Writing"
theme = "ghostwriter"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "Angela Writing"
    description = "My description"
    github = "https://github.com/angelaferguson"
    linkedin = "https://www.linkedin.com/in/angelaferguson-techwriter/"
    email = "angela83f@gmail.com"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"
